[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false

[client]
toolbarMode = "minimal"